use_frameworks!

target 'KJTools_Swift_Example' do
  pod 'KJTools_Swift', :path => '../'

  target 'KJTools_Swift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
