use_frameworks!

target 'KJTools_Swift_Example' do
  pod 'KJTools_Swift', :path => '../'
  
#  --use-libraries --allow-warnings

  # pod 'Kingfisher'

  #  CocoaPods 给每个库单独指定 Swift 版本教程
  #  https://www.jianshu.com/p/aa8bcf3897a0

end
